[package]
name = "continue_notation"
version = "0.1.0"
authors = ["Edmund Smith <edmund.pd.smith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.0"
syn = {version = "1.0.0", features = ["full", "fold"]}
quote = "1.0"
continue_notation_macro = {path="continue_notation_macro"}
